CREATE TABLE IF NOT EXISTS HOSTEL
(
    id              INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255),
    address         VARCHAR(255),
    capacity        INT,
    price_per_night DECIMAL(10, 2),
    available       BOOLEAN,
    created_at      TIMESTAMP
);

-- Seed 50 hostels
INSERT INTO HOSTEL (name, address, capacity, price_per_night, available, created_at)
VALUES ('Backpackers Inn', '12 Hill St', 20, 15.00, TRUE, CURRENT_TIMESTAMP),
       ('City Hostel', '88 Main Ave', 40, 22.50, TRUE, CURRENT_TIMESTAMP),
       ('Quiet Corner', '5 Lake Rd', 10, 12.00, FALSE, CURRENT_TIMESTAMP),
       ('Sunset Lodge', '101 Sunset Blvd', 25, 18.75, TRUE, CURRENT_TIMESTAMP),
       ('Mountain View', '77 Peak St', 30, 20.00, TRUE, CURRENT_TIMESTAMP),
       ('Lakeside Hostel', '9 Lake Shore Dr', 18, 14.50, TRUE, CURRENT_TIMESTAMP),
       ('Urban Stay', '200 City Center Rd', 35, 24.00, TRUE, CURRENT_TIMESTAMP),
       ('Forest Retreat', '55 Pine Ave', 12, 13.00, FALSE, CURRENT_TIMESTAMP),
       ('Riverside Rest', '3 River Walk', 22, 17.25, TRUE, CURRENT_TIMESTAMP),
       ('Coastal Cabin', '444 Ocean Rd', 16, 19.00, TRUE, CURRENT_TIMESTAMP),
       ('Harbor House', '78 Dock St', 28, 21.00, TRUE, CURRENT_TIMESTAMP),
       ('Garden Hostel', '14 Rose Ln', 15, 13.75, TRUE, CURRENT_TIMESTAMP),
       ('City Lights', '310 Metro Ave', 42, 26.00, TRUE, CURRENT_TIMESTAMP),
       ('Country Inn', '5 Meadow Way', 20, 16.00, FALSE, CURRENT_TIMESTAMP),
       ('Skyline Stay', '900 Skyline Dr', 33, 23.50, TRUE, CURRENT_TIMESTAMP),
       ('Canyon Camp', '66 Canyon Rd', 14, 12.50, TRUE, CURRENT_TIMESTAMP),
       ('Bay Breeze', '21 Bay St', 19, 18.00, TRUE, CURRENT_TIMESTAMP),
       ('Hilltop Hostel', '8 Summit Ave', 24, 17.00, TRUE, CURRENT_TIMESTAMP),
       ('Downtown Dorms', '101 Center St', 50, 28.00, TRUE, CURRENT_TIMESTAMP),
       ('Maple House', '77 Maple St', 11, 11.00, FALSE, CURRENT_TIMESTAMP),
       ('Elm Stay', '9 Elm Rd', 13, 12.25, TRUE, CURRENT_TIMESTAMP),
       ('Cedar Cabin', '45 Cedar Ct', 17, 15.25, TRUE, CURRENT_TIMESTAMP),
       ('Birch Base', '88 Birch Blvd', 21, 16.75, TRUE, CURRENT_TIMESTAMP),
       ('Oak Outlook', '6 Oak Ln', 26, 19.50, TRUE, CURRENT_TIMESTAMP),
       ('Spruce Suites', '123 Spruce Ave', 18, 14.25, TRUE, CURRENT_TIMESTAMP),
       ('Palm Place', '3 Palm Dr', 29, 22.25, TRUE, CURRENT_TIMESTAMP),
       ('Shoreline Stay', '64 Shoreline Rd', 23, 20.75, TRUE, CURRENT_TIMESTAMP),
       ('Harbor Haven', '81 Harbor Rd', 27, 21.50, TRUE, CURRENT_TIMESTAMP),
       ('Pier Point', '72 Pier Ln', 31, 23.75, TRUE, CURRENT_TIMESTAMP),
       ('Marina Manor', '33 Marina Ave', 34, 24.50, TRUE, CURRENT_TIMESTAMP),
       ('Beacon Base', '16 Beacon St', 12, 13.50, FALSE, CURRENT_TIMESTAMP),
       ('Island Inn', '5 Island Way', 22, 19.25, TRUE, CURRENT_TIMESTAMP),
       ('Peninsula Place', '7 Peninsula Rd', 28, 21.25, TRUE, CURRENT_TIMESTAMP),
       ('Delta Dorm', '2 Delta St', 32, 23.00, TRUE, CURRENT_TIMESTAMP),
       ('Lagoon Lodge', '4 Lagoon Ln', 20, 18.50, TRUE, CURRENT_TIMESTAMP),
       ('Coral Cottage', '9 Coral Rd', 14, 14.00, TRUE, CURRENT_TIMESTAMP),
       ('Sandbar Stay', '19 Sandbar Ave', 24, 17.75, TRUE, CURRENT_TIMESTAMP),
       ('Cliffside Cabin', '27 Cliffside Rd', 18, 16.25, TRUE, CURRENT_TIMESTAMP),
       ('Meadow Mews', '6 Meadow Ln', 15, 13.25, TRUE, CURRENT_TIMESTAMP),
       ('Prairie Place', '12 Prairie Rd', 16, 14.75, TRUE, CURRENT_TIMESTAMP),
       ('Savanna Stay', '8 Savanna Ct', 19, 18.25, TRUE, CURRENT_TIMESTAMP),
       ('Valley View', '44 Valley Rd', 21, 19.00, TRUE, CURRENT_TIMESTAMP),
       ('Brookside Base', '3 Brookside Ln', 17, 15.75, TRUE, CURRENT_TIMESTAMP),
       ('Hillside Hostel', '11 Hillside Rd', 20, 16.50, TRUE, CURRENT_TIMESTAMP),
       ('Grove Guesthouse', '22 Grove Ave', 23, 20.00, TRUE, CURRENT_TIMESTAMP),
       ('Alpine Abode', '77 Alpine Rd', 25, 21.75, TRUE, CURRENT_TIMESTAMP),
       ('Tundra Terrace', '5 Tundra Way', 10, 12.25, FALSE, CURRENT_TIMESTAMP),
       ('Delta Dwell', '13 Delta Rd', 26, 22.75, TRUE, CURRENT_TIMESTAMP),
       ('Harbor Hub', '18 Harbor Ln', 30, 24.75, TRUE, CURRENT_TIMESTAMP),
       ('Bay Base', '7 Bay Ave', 28, 22.00, TRUE, CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS REVIEW
(
    id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    text    VARCHAR(500) NOT NULL,
    author  VARCHAR(100) NOT NULL,
    created TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO REVIEW (text, author, created)
VALUES ('I came for the WiFi, I stayed for the free breakfast. 10/10, would nap again!', 'Sleepy Sam',
        CURRENT_TIMESTAMP),
       ('Lost my socks, found new friends. Hostel magic!', 'Wanderlust Wendy', CURRENT_TIMESTAMP),
       ('Showers hotter than my love life. Highly recommend.', 'Steamy Steve', CURRENT_TIMESTAMP),
       ('Beds so comfy, I missed my train. Twice.', 'Snooze Cruise', CURRENT_TIMESTAMP),
       ('Staff laughed at my jokes. Or maybe at my hair. Either way, 5 stars!', 'Punny Paul', CURRENT_TIMESTAMP),
       ('I thought I was checking into a movie set. Turns out, it was just this awesome hostel!', 'Leonardo DiCaprio',
        CURRENT_TIMESTAMP),
       ('Even my entourage was impressed. And they are hard to please.', 'Dwayne Johnson', CURRENT_TIMESTAMP),
       ('I asked for a quiet room. They gave me a fan club instead!', 'Tom Holland', CURRENT_TIMESTAMP),
       ('The only thing missing was a red carpet. But the breakfast made up for it.', 'Scarlett Johansson',
        CURRENT_TIMESTAMP),
       ('I came for a night, stayed for a week. My agent is still looking for me.', 'Ryan Reynolds', CURRENT_TIMESTAMP),
       ('If hostels gave Oscars, this one would win Best Picture.', 'Meryl Streep', CURRENT_TIMESTAMP),
       ('I tried to go incognito, but the staff recognized me by my laugh.', 'Will Smith', CURRENT_TIMESTAMP),
       ('I’ve stayed in five-star hotels, but this place has five-star vibes.', 'Zendaya', CURRENT_TIMESTAMP),
       ('The only drama here is who gets the top bunk.', 'Chris Hemsworth', CURRENT_TIMESTAMP),
       ('I’d film my next blockbuster here if I could.', 'Gal Gadot', CURRENT_TIMESTAMP);
